name: Agentic Conversation Simulator
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - pip:
    - streamlit>=1.30.0
    - requests>=2.28.0
    - pyhocon>=0.9.0
    - psutil>=5.9.0
    - GPUtil>=1.4.0
